sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t fabioq/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true fabioq/docker-react-travis npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-travis"
  env: "DockerReactTravis-env"
  bucket_name: "elasticbeanstalk-eu-west-2-319188801678"
  bucket_path: "docker-react-travis"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY